# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0431612a2a4acf81d4a076d25c76a57f26df613f7c2011fa9fcc94e03e79e4ef9c0adbe69c385a685f368067ccbf1131a8d9886b76640e35d96e63e929cc8d3d

test:
  secret_key_base: 12e823f4b76c529b04f13b3845f8757226d51a1068191bd4944b99a26e6a1805d1a4510b7eed44d4b4079731be5939e244d93eb0b3aa394a4786d46f41dc8160

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
